### ISSUE TITLE
Erreur lors d'un précédent `git merge`

### ISSUE THREAD

**Issue by paternal** [Pyromaths/pyromaths#14]
Voir [lignes 64 à 76 du fichier `utils/make_packages.sh`](https://github.com/Pyromaths/pyromaths/blob/6a155306022acc8e430b759842f5f5d4722d6c96/utils/make_packages.sh#L64).

@JeromeO, je te laisse corriger, vu que je pense que [c'est toi le responsable](https://github.com/Pyromaths/pyromaths/blame/6a155306022acc8e430b759842f5f5d4722d6c96/utils/make_packages.sh#L64).

**Comment by JeromeO** [comment]
Corrigé 527f1bcb54b1e1a9c6e2c0c149b7e7f643536cb2
