### ISSUE TITLE
Bug dans l'exercice Sd2aRacines

### ISSUE THREAD

**Issue by paternal** [Pyromaths/pyromaths#16]
Voir le fichier [exercice.pdf](https://github.com/Pyromaths/pyromaths/files/2019799/exercice.pdf).

Dans le corrigé des polynômes P et R : 
- il manque un + dans l'expression : `√2x√7` au lieu de `√2x+√7` (idem pour le polynôme R) ;
- à la même ligne, le √7 est entre parenthèses alors qu'il ne devrait pas.

-- Louis

**Comment by JeromeO** [comment]
Corrigé dans le commit 9444b2ecaeaf7d69c99ef5d3f95d51a012cc77c9
Tu as réussi à me faire refaire du code après des années d'arrêt je crois :)

**Comment by paternal** [comment]
😎
