### ISSUE TITLE
Exercice inutile

### ISSUE THREAD

**Issue by paternal** [Pyromaths/pyromaths#19]
L'exercice EquationGraphique est non terminé et donc inutile. Je me trompe ?

https://github.com/Pyromaths/pyromaths/blob/58207ac78fff8119621d2f4b232e27f6b8ea272f/src/pyromaths/ex/lycee/equations.py

**Comment by JeromeO** [comment]
Oui. C'est pour cela que le titre est commenté, afin qu'il n'apparaisse pas dans la liste.
Ceci dit, j'avais oublié que j'avais commencé ce travail. Il va falloir que je le termine en utilisant le template.

**Comment by paternal** [comment]
Noté.
